package moviefyPackge.moviefy.domain.dto.MoviteDtos;

import lombok.Data;
/**
 * DTO representing a popular movie with its income for charting purposes.
 * Fields:
 * - movieTitle: The title of the movie.
 * - totalIncome: The total income generated by the movie (in system currency).
 */
@Data
public class PopularMovieChartDto {

    private String movieTitle;
    private Integer totalIncome;

    public PopularMovieChartDto(String movieTitle,Integer totalIncome){
        this.movieTitle=movieTitle;
        this.totalIncome = totalIncome;
    }

}
